import { Apartment } from '@/models/apartment';

export const apartments: Apartment[] = [
  {
    id: 'psa-ph',
    name: 'Presidential Service Apartment PH',
    slug: 'presidential-service-apartment-ph',
    location: {
      address: { street: 'No. 4, Sam B, Plot 493 Aka Street, Eagle Island', city: 'Port Harcourt', state: 'Rivers', country: 'Nigeria' },
      coordinates: { lat: 4.7837725, lng: 6.8946587 },
      mapUrl: 'https://maps.google.com/?q=4.7837725,6.8946587',
    },
    summary:
      'Premium serviced apartment offering modern amenities and comfort in Port Harcourt.',
    description: `<h1><strong>PRESIDENTIAL SERVICE APARTMENTS PH</strong></h1><p>At Presidential Service Apartments, we love making our guests feel comfortable, energized and productive when they stay with us. We do this by combining premium accommodations with great services.<br />As one of our guests, we know how busy you are. And, we know the importance of a good night's sleep. That's why we have theSwissSleep Advantage. It's our way of helping you fall asleep and rest well, waking up to take on the day.</p><ul><li>Fully equipped kitchen with utensils.</li><li>In-house laundry services.</li><li>Flat-screen LED TV.</li><li>High-speed fiber optic internet.</li><li>24 hours electricity.</li></ul><p>We also offer state of the art facilities for small to medium-sized groups and informal meeting spaces for our guests to relax unwind and socialize after a long day. To plan your next getaway, check our variety of Furnished Apartments deals to find great offers, packages and discounts.</p><p>Stay in the heart of Port Harcourt.</p><p>Contemporary, convenient and&nbsp;<a href="http://www.moevenpick-hotels.com/en/middle-east/qatar/doha/hotel-doha/things-to-do/">perfectly positioned</a>, the upscale Presidential Apartments PH is ideal for business travelers. Just 30 minutes from the Airport, Presidential Apartment is centrally located on EAGLE ISLAND.<br /><br /></p><h2><strong>THE LOBBY</strong></h2><p>The moment you enter the lobby; you will feel the personalized hospitality that makes the Apartments so different. Its warmth and relaxed grace create a distinctive welcoming ambiance that is sensed throughout our Special touches and the smell of Africanincense carry you to a world of enchantment.</p><h2>APARTMENTS&nbsp;</h2><p>Featuring 10 Apartments,the capaciousApartments, are custom-made for business travel and perfect for relaxing leisure guests. Elegantly combining style and comfort with generous space to work and relax. Andsurroundings of a 5stars&rsquo;, with special amenities from our owngarden Tastefully decorated by a famous international designer whose international touch has smoothly blended into the Swiss spirit.</p><h2>THE FOOD</h2><p>Welcome to an exquisite Nigerian, Continental,and fusion Gastronomic healthy experience. Our cuisine is prepared with world standard foods.</p><h2>RESTAURANT</h2><p><a href="http://www.moevenpick-hotels.com/en/middle-east/qatar/doha/hotel-doha/restaurants/">Culinary creativity</a>&nbsp;is the signature of the Presidential Apartments PH. Whether looking for a casual coffee, a business brunch, we have something for everyone from theme nights and &agrave; la carte to snacks and cocktails. Lunching or Dining at the restaurant is truly delightful. Enjoy a wide spectrum of cuisines, complemented by a hearty service.</p>`,
    amenities: [
      '24/7 Power',
      'High‑speed Wi‑Fi',
      'Parking',
      'Security',
      'Housekeeping',
      'Fully equipped kitchen with utensils.',
      'In-house laundry services',
      'Flat-screen LED TV',
      'High-speed fiber optic internet'
    ],
    featuredMedia: {
      url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FOTHERS%2FIMG_6309.jpg?alt=media&token=1cd49059-abb5-4c02-a74d-6298328117d0',
      alt: 'Deluxe bedroom',
      type: 'image',
      width: 1080,
      height: 1920,
      caption: 'Building exterior',
    },
    gallery: [
      {
        url: 'https://youtube.com/shorts/n9pC-kHSkd4',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/TdsWUqWQ7r4',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/1vrzIrYEkH4',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/H87GIhbXbE0',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/pm_nSCGmi-Y',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/RK1xNdby0-4',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
      {
        url: 'https://youtube.com/shorts/IF0ESbYlpls',
        type: 'video',
        width: 1080,
        height: 1920,
        alt: 'Lobby',
        caption: 'Lobby',
      },
    ],
    rating: 4.8,
    reviewsCount: 124,
    contact: {
      phone: '+234-800-000-0000',
      email: 'stay@presidentialserviceapartment.ng',
      website: 'https://presidentialserviceapartment.ng',
    },
    policies: {
      checkIn: '14:00',
      checkOut: '11:00',
      minStayNights: 1,
      maxStayNights: 30,
      smoking: false,
      pets: false,
      children: true,
      cancellation: 'Free cancellation up to 48 hours before check‑in.',
      houseRules: [
        'No parties',
        'Quiet hours 22:00–07:00',
        'Valid ID required at check‑in',
      ],
    },
    rate: {
      currency: 'NGN',
      basePricePerNight: 65000,
      cleaningFee: 5000,
      securityDeposit: 50000,
      taxesIncluded: true,
    },
    tags: ['shortlet', 'serviced', 'Port Harcourt', 'Wi‑Fi', 'parking'],
    createdAt: '2024-01-15T09:00:00.000Z',
    updatedAt: '2024-10-20T12:30:00.000Z',
    rooms: [
      {
        id: 'psa-ph-11b-room',
        name: '11B Room',
        description: 'Spacious suite with city view and modern finishings.',
        capacity: 2,
        bedType: 'King',
        pricePerNight: 0,
        amenities: [
          'Air Conditioning',
          'Wi‑Fi',
          'Smart TV',
          'Kitchenette',
          '24/7 Power',
        ],
        media: [
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6348.jpg?alt=media&token=73641aa6-131a-40cd-875f-a75f6173706c',
            alt: 'Deluxe living area',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe living area',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6349.jpg?alt=media&token=aa5974c4-4ce7-44c4-8641-c3e0b0f5378f',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6350.jpg?alt=media&token=4cac1f79-3e44-4417-b7dc-5e36724828ac',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6351.jpg?alt=media&token=b74e55d9-12e5-4393-8acd-4a5899a3a8b2',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6352.jpg?alt=media&token=187502de-6924-4776-8ca2-3ecc3632d703',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6353.jpg?alt=media&token=ab17b994-7132-426c-a87c-44f726939662',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6355.jpg?alt=media&token=2416ec39-e4fb-42da-afcc-0db0272c74d7',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6359.jpg?alt=media&token=7e568fb3-0af6-4d59-90ac-bbc32b53a3de',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6360.jpg?alt=media&token=f4094b5e-16d1-4111-aabb-c7f0dffb7d02',
            alt: '...',
            type: 'image',
            width: 1080,
            height: 1920,
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6362.jpg?alt=media&token=eb601c90-3552-4645-b6ae-d4cb65825185',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6363.jpg?alt=media&token=90ce6f4d-b6c7-41d3-af93-23e0bf1634f9',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6364.jpg?alt=media&token=d56028d4-f8d4-4dbc-b7bf-6ceb9e48954f',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6365.jpg?alt=media&token=aa422411-1625-4703-9283-972a793af03f',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6367.jpg?alt=media&token=1dcf52d4-ea3a-469d-86b4-e0fc38ba0977',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6368.jpg?alt=media&token=a48e80c3-77ed-44cd-bffc-cdf619296d1c',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6369.jpg?alt=media&token=1fbfa331-9f51-43f6-b0b7-13f5f2371267',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6370.jpg?alt=media&token=a5999de2-03e3-45db-ba37-b7ff90ba29a0',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6371.jpg?alt=media&token=4fb54029-9016-433e-be70-092165fa2f11',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6372.jpg?alt=media&token=40b4b28e-50b5-424c-b2d5-fd132d24f94c',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6373.jpg?alt=media&token=d5884e3f-b4da-4215-97ea-624e79ad7321',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6374.jpg?alt=media&token=22e98a30-8cf5-4d13-8403-958df1205b1e',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6375.jpg?alt=media&token=424a6acd-4270-4cd9-8e26-ac62aec23490',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6376.jpg?alt=media&token=f41b1f14-bbcc-4a2f-a4b3-c261005216e8',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6377.jpg?alt=media&token=676fbac2-faea-452e-8093-564a54826423',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6378.jpg?alt=media&token=e1691459-088f-4d21-bd49-4ddadeb60517',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6379.jpg?alt=media&token=8dbdbe38-11ba-425d-bfc6-82f3a5de6de0',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6381.jpg?alt=media&token=815b1d77-112c-4e22-ab2a-7b8fa8a3e4f8',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6382.jpg?alt=media&token=960e39e0-56a5-4049-8bfc-ba906cfa2721',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F11B%2FIMG_6383.jpg?alt=media&token=6d09402f-c229-4539-9044-a65ffeea29ee',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
        ],
      },
      {
        id: 'psa-ph-room-22a',
        name: 'Room 22A',
        description: 'Executive suite with workspace and premium furnishing.',
        capacity: 3,
        bedType: 'Queen',
        pricePerNight: 80000,
        amenities: [
          'Workspace',
          'Wi‑Fi',
          'Smart TV',
          'Kitchenette',
          'City View',
        ],
        media: [
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6314.jpg?alt=media&token=416cf862-ddbb-4018-b852-eb51d54d8c62',
            alt: 'Executive living area',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive living area',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6315.jpg?alt=media&token=9243caa4-696b-438e-a96d-937155fccfae',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6317.jpg?alt=media&token=6ae11737-63ec-48c4-a057-83deda88f1bf',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6318.jpg?alt=media&token=6efea821-9c57-4b74-9276-5ae723048db0',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6319.jpg?alt=media&token=7f16d6d6-7127-46c0-977f-7b698060a468',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6320.jpg?alt=media&token=84201ade-b40d-4269-95ab-180c32aa97da',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6321.jpg?alt=media&token=92774f74-f054-4760-a308-c13117d3430c',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6322.jpg?alt=media&token=f678ae78-5376-49ff-9b0d-e266963f385b',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6323.jpg?alt=media&token=ab3360f4-d605-4cc9-a17b-7e6cba8e18f9',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6325.jpg?alt=media&token=042e9e50-bf44-4ff2-8c78-dcf28256281a',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6326.jpg?alt=media&token=8bdc65c2-3fc5-4444-af81-300a087d213a',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6327.jpg?alt=media&token=d6cdd3d1-d17c-4e4c-a501-cba541eeeae9',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6328.jpg?alt=media&token=4bf8c55b-cfe8-460f-a08e-44eca9f3e572',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6330.jpg?alt=media&token=3f7bcf48-bd77-4329-b1b4-b67a6785714f',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6331.jpg?alt=media&token=f7094f5a-63df-45fc-ab13-d4ca4106b34b',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6332.jpg?alt=media&token=d546253c-6479-4bdb-9344-c2069fba430a',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6333.jpg?alt=media&token=11e7200c-6d79-4462-88ad-7077074959ef',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6334.jpg?alt=media&token=5fae31af-f945-4d6b-99df-d8e1fe1693f0',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6335.jpg?alt=media&token=7b25e235-3e9c-44d2-acd9-d866ed691392',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6336.jpg?alt=media&token=09d21f9d-cb8f-4317-8326-e76a9253687e',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6337.jpg?alt=media&token=1bd4a776-773c-49a4-b3fb-66b49e00094d',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6338.jpg?alt=media&token=1f9d1045-d6b2-4661-af28-b25da3f80856',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6339.jpg?alt=media&token=6bb4c70d-1230-4a19-a010-1f47448a9aa0',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6340.jpg?alt=media&token=c1654d3a-2483-42f5-bbcd-235d6ceb6aad',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2F22A%2FIMG_6342.jpg?alt=media&token=3d8bc67c-ad05-4489-8926-4a581acde200',
            alt: 'Executive bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Executive bedroom',
          },
        ],
      },
      {
        id: 'psa-ph-ground-floor',
        name: 'Ground Floor',
        description: 'Deluxe suite with workspace and premium furnishing.',
        capacity: 3,
        bedType: 'Queen',
        pricePerNight: 1000,
        amenities: ['Wi-Fi', 'TV', 'Air Conditioning', 'Heating'],
        media: [
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6394.jpg?alt=media&token=d2bfdaf0-fdc2-4b35-b6c1-1ff0323e3351',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6395.jpg?alt=media&token=315bd4fd-690a-47d7-824f-c797a850367e',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6396.jpg?alt=media&token=0e1c41f0-7fc8-4576-9db6-c916cb96bb60',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6397.jpg?alt=media&token=0f6596f3-8f59-4c9d-988f-b5cfe277276f',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6398.jpg?alt=media&token=af9a2d18-9f1f-40f7-be17-2d5377e1cc63',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6399.jpg?alt=media&token=ebfe57ea-024a-49da-abaf-7ba1922a0e7a',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6400.jpg?alt=media&token=be1ce67a-1388-4a8f-a69c-1db41dea4b1a',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6401.jpg?alt=media&token=98126a4f-633c-42f7-b88a-d8877fabdcbd',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6402.jpg?alt=media&token=2def6011-280f-4920-a7ac-77913fa34649',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6403.jpg?alt=media&token=b700d5e4-adb7-481d-8973-0a0aa0507dc0',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6404.jpg?alt=media&token=987e14e1-f374-4a34-8875-c3b22992d89b',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6405.jpg?alt=media&token=ba351e85-038a-48e8-a899-21424c2cf62e',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6406.jpg?alt=media&token=07abf506-60cb-4d42-889b-227031c9cbe7',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6407.jpg?alt=media&token=755e909b-92e8-4f9d-a64e-67678d0c52be',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6408.jpg?alt=media&token=ea88ae29-4346-4a08-8358-380508b3a976',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6409.jpg?alt=media&token=6315273f-7dc7-4546-90a4-a470e4e133ee',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6410.jpg?alt=media&token=91583a4e-1301-477f-8a28-3bd3a6ddf576',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6411.jpg?alt=media&token=607349b5-2b2d-4311-b172-4270e6f889c8',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6412.jpg?alt=media&token=4c545980-a3e3-405b-946b-5a64a799d049',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6414.jpg?alt=media&token=e0221161-c9d6-49f8-a4b7-7c4722cc948d',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6415.jpg?alt=media&token=c1246c69-5363-4f75-bf8a-7ba98e54712f',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6416.jpg?alt=media&token=124c11a7-e2de-4079-93b2-a0b527791c4d',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6417.jpg?alt=media&token=9121a461-3207-4b83-b403-ff19e2a92e1a',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6418.jpg?alt=media&token=3e135b75-e569-4b02-a570-5b03874432d5',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6419.jpg?alt=media&token=b79d5c4f-b191-474b-b1e4-24df207cba4c',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6420.jpg?alt=media&token=5e848aea-1fda-4766-86f1-a1fa93646201',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6421.jpg?alt=media&token=dfb48ce3-643d-4e02-a2c1-f285452397ed',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6422.jpg?alt=media&token=d3bc234e-7376-40af-8fda-3424059660ea',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6423.jpg?alt=media&token=7b72cd80-7248-4517-b0c6-6415b126e9e2',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6424.jpg?alt=media&token=ac7597b9-61e5-4dd7-8046-d997fb67364b',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6425.jpg?alt=media&token=342915e4-e2b3-4723-a035-c89ac1e616d4',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6426.jpg?alt=media&token=e9b83c6b-d93c-4b26-8beb-03363daf30ae',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6427.jpg?alt=media&token=4f9c4f94-22b1-4730-ae34-bbf5c7b161a7',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6428.jpg?alt=media&token=fd910df8-5b7e-434d-8e3d-0abc3d06ff1e',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6429.jpg?alt=media&token=210380f0-fdc5-4508-a1d2-41f26d2e6408',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6430.jpg?alt=media&token=5cb12488-6b33-4f57-a86d-c764b4201fa7',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6431.jpg?alt=media&token=2ab2a3b1-0b0f-4ccd-8f4f-40d77a94dfa2',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6432.jpg?alt=media&token=52d22ebd-6b57-4b19-b373-aef17f28169c',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6433.jpg?alt=media&token=7f44c000-8c37-4fc4-bee2-932a51bffd2e',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
          {
            url: 'https://firebasestorage.googleapis.com/v0/b/ayha-the-market.firebasestorage.app/o/presidentialserviceapartments.ng%2FGROUND_FLOOR%2FIMG_6434.jpg?alt=media&token=b48a11c0-2daa-49b3-bfc0-65ae72b5664d',
            alt: 'Deluxe bedroom',
            type: 'image',
            width: 1080,
            height: 1920,
            caption: 'Deluxe bedroom',
          },
        ],
      },
    ],
  },
];
